version: '3'
services:
  node-app:
    restart: on-failure
    tty: true
    stdin_open: true
    image: fontys-s6-gateway
    build: 
      context: ./
    ports:
      - "3002:3002"
    volumes:
      - ./:/usr/src/app
    networks:
      - app_network
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
  
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5673:5672
        - 15673:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - app_network
networks:
  app_network:
    driver: bridge
