name: Build and test container app

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
        
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USER_NAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: index.docker.io/${{ secrets.DOCKER_HUB_USER_NAME }}/gateway:${{ github.sha }}
        file: ./Dockerfile
        
